# Generated by Django 5.2.6 on 2025-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsLearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('data', 'Data Science'), ('design', 'Design')], default='web', max_length=20),
        ),
    ]
